{{-- resources/views/accounting/profit-loss-pdf.blade.php --}}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body        { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; }
    h2          { text-align:center; margin-bottom:4px; font-size:16px; }
    .subtitle   { text-align:center; color:#666; margin-bottom:16px; font-size:11px; }
    table       { width:100%; border-collapse:collapse; margin-bottom:16px; }
    th          { background:#343a40; color:#fff; padding:7px 10px; text-align:left; font-size:11px; }
    td          { padding:6px 10px; border-bottom:1px solid #dee2e6; font-size:11px; }
    .text-right { text-align:right; }
    .text-center{ text-align:center; }
    .success    { color:#28a745; font-weight:bold; }
    .danger     { color:#dc3545; font-weight:bold; }
    .primary    { color:#007bff; font-weight:bold; }
    .warning    { color:#ffc107; font-weight:bold; }
    .tfoot td   { background:#f8f9fa; font-weight:bold; border-top:2px solid #343a40; }
    .badge      { padding:2px 7px; border-radius:10px; font-size:10px; }
    .badge-success { background:#d4edda; color:#155724; }
    .badge-warning { background:#fff3cd; color:#856404; }
    .badge-danger  { background:#f8d7da; color:#721c24; }
    .footer     { margin-top:20px; text-align:center; color:#888; font-size:10px; border-top:1px solid #dee2e6; padding-top:8px; }
</style>
</head>
<body>

<h2>Profit & Loss Report</h2>
<div class="subtitle">
    {{ \Carbon\Carbon::parse($fromMonth.'-01')->format('F Y') }}
    — {{ \Carbon\Carbon::parse($toMonth.'-01')->format('F Y') }}
    &nbsp;|&nbsp; Generated: {{ now()->format('d M Y h:i A') }}
</div>

{{-- Grand Summary --}}
<table>
    <tr>
        <th>Total Income</th>
        <th>Total Expense</th>
        <th>Net Profit</th>
        <th>Profit Margin</th>
    </tr>
    <tr>
        <td class="success">BDT {{ number_format($grandIncome, 2) }}</td>
        <td class="danger">BDT {{ number_format($grandExpense, 2) }}</td>
        <td class="{{ $grandProfit >= 0 ? 'primary' : 'warning' }}">BDT {{ number_format($grandProfit, 2) }}</td>
        <td class="text-center">{{ $grandMargin }}%</td>
    </tr>
</table>

{{-- Monthly Breakdown --}}
<table>
    <thead>
        <tr>
            <th>Month</th>
            <th class="text-right">Monthly Bill</th>
            <th class="text-right">Other Income</th>
            <th class="text-right">Total Income</th>
            <th class="text-right">Total Expense</th>
            <th class="text-right">Net Profit</th>
            <th class="text-center">Margin</th>
        </tr>
    </thead>
    <tbody>
        @foreach($rows as $row)
        <tr>
            <td><strong>{{ $row['month_label'] }}</strong></td>
            <td class="text-right">{{ number_format($row['monthly_bill']) }}</td>
            <td class="text-right">{{ number_format($row['manual_income']) }}</td>
            <td class="text-right success">{{ number_format($row['total_income']) }}</td>
            <td class="text-right danger">{{ number_format($row['total_expense']) }}</td>
            <td class="text-right {{ $row['net_profit'] >= 0 ? 'primary' : 'warning' }}">
                {{ number_format($row['net_profit']) }}
            </td>
            <td class="text-center">{{ $row['margin'] }}%</td>
        </tr>
        @endforeach
    </tbody>
    @if(count($rows) > 1)
    <tfoot>
        <tr class="tfoot">
            <td><strong>Grand Total</strong></td>
            <td class="text-right">—</td>
            <td class="text-right">—</td>
            <td class="text-right success">BDT {{ number_format($grandIncome) }}</td>
            <td class="text-right danger">BDT {{ number_format($grandExpense) }}</td>
            <td class="text-right {{ $grandProfit >= 0 ? 'primary' : 'warning' }}">
                BDT {{ number_format($grandProfit) }}
            </td>
            <td class="text-center">{{ $grandMargin }}%</td>
        </tr>
    </tfoot>
    @endif
</table>

<div class="footer">
    This report was automatically generated by ISP Management System
</div>

</body>
</html>
